### ISSUE TITLE
"designed to run on Windows 10" error

### ISSUE THREAD

**Issue by J0ssel1n** [au2001/icloud-passwords-firefox#25]
Hello.
I run Firefox and Windows 11 on my computer.
I have installed iCloud Drive, Passwords, etc...
And I get this error :
![image](https://github.com/aurelien-garnier/icloud-passwords-firefox/assets/92841489/a27b0537-2645-4d3f-9663-14f2ae3a2c38)
If I press "retry", there is the same error.

How can I fix it?

**Comment by Suhaybu** [comment]
Hey, I've managed to get the extension tp work on Windows 11. However I believe it's because of the steps I followed in another iCloud Passwords for Firefox repo (not my work). While that other extension is outdated, the steps provided there seem's to work and helped me get this same extension working on Windows 11.

Repo: https://github.com/ArakawaHenri/iCloudPasswords_for_Firefox

## Steps
- Make sure you have enabled the extension for at least Edge or Chrome.
- Then from Step 3 in the linked repo, download and run the linked tool to give Firefox permission to interact with the Windows Client.

**Comment by Justdave-AU** [comment]
Will be great when this is solved. Works perfectly  in Chrome on Windows machine.
