### ISSUE TITLE
VirusTotal Flag and Apple Relation Question

### ISSUE THREAD

**Issue by ProLiteAD** [au2001/icloud-passwords-firefox#53]
I did a quick VirusTotal scan and got 3 flags. 
![image](https://github.com/user-attachments/assets/ce281758-7516-4e86-8fe3-16da28b21211)

- Is this normal?
- Also, what is the relationship between this repo and Apple?

I installed the Firefox extension "iCloud Passwords", and surprisingly was sent to here.

**Comment by au2001** [comment]
Not sure why VirusTotal considers it malicious, could be because it has to edit the Windows Registry and requires admin priviledges
The source code is available here if you want to check that it does not encrypt any file: [install_windows.go](https://github.com/au2001/icloud-passwords-firefox/blob/main/scripts/install/install_windows.go)
It only modifies the file `C:\Program Files\Mozilla Firefox\FirefoxPwdMgrHostApp_manifest.json` which allows it to communicate with the iCloud desktop companion

As for the relationship with Apple, this repo is privately owned and maintained by me
Since last week, Apple has ownership over the Firefox extension on the AMO store, but they still use my code (this repo), as theirs is (supposedly) not ready yet
So there is no _official_ Firefox extension for iCloud Passwords yet
